package com.gmail.chickenpowerrr.chickentest.generator.number;

import com.gmail.chickenpowerrr.chickentest.generator.restrictions.ParameterRestriction;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Describes the minimum and maximum value to be generated
 * by an {@link IntGenerator}.
 *
 * @author Mark van Wijk
 * @since 1.0.0
 */
@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
@ParameterRestriction
public @interface IntRange {

  int DEFAULT_MIN = 0;
  int DEFAULT_MAX = Integer.MAX_VALUE;

  /**
   * Returns the minimum value (included) to be generated
   * by the {@link IntGenerator}. DEFAULT_MIN by default.
   */
  int min() default DEFAULT_MIN;

  /**
   * Returns the maximum value (excluded) to be generated by
   * the {@link IntGenerator}. DEFAULT_MAX by default.
   */
  int max() default DEFAULT_MAX;
}
