package com.gmail.chickenpowerrr.chickentest.generator;

/**
 * A restriction on the values to be generated by the
 * corresponding {@link Generator}.
 *
 * @author Mark van Wijk
 * @since 1.0.0
 */
public @interface ParameterRestriction {

}
